model:
  name: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
  max_length: 512
  batch_size: 1
  device: null  # Remove device specification
  quantization:
    enabled: false
    bits: 8

inference:
  max_length: 100
  temperature: 0.7
  top_p: 0.9
  num_return_sequences: 1

training:
  enabled: false
  learning_rate: 2e-5
  num_epochs: 1
  gradient_accumulation_steps: 4
  warmup_steps: 100